/**
* RECOMMENDATIONS
* Note: this table tracks all the recommendations for things to eat, do, learn.
* Requires PostGIS. To enable head to https://app.supabase.io/project/{id}/database/extensions
*/
create type recommendation_category as enum ('eat', 'do', 'learn');
create type cost_type as enum ('free', 'paid');
create table recommendations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  url text not null,
  image_url text not null,
  category recommendation_category not null,
  location geography(point), -- insert into recommendations (location) values ('SRID=4326;POINT(longitude latitude)');
  source text,
  cost cost_type,
  clicks bigint default 0,
  downvotes bigint default 0,
  expiration_date timestamp with time zone,
  approved boolean
)